// Additional information and deep dive content for lessons 19-54
// Merged into seed data during seeding

const lessonsAdditional = {
  19: {
    additionalInfo: "Parallel lines have the same slope (m) but different y-intercepts — they never intersect. Perpendicular lines have slopes that are negative reciprocals: if m₁=2, then m₂=-1/2.\n\nSystems of linear equations: consistent (at least one solution), inconsistent (no solution — parallel lines), dependent (infinite solutions — same line).\n\nMatrix representation: a system Ax=b can be solved with Gaussian elimination or matrix inversion. Essential for computer graphics, economics, and engineering.",
    deepDive: "Linear programming optimizes an objective function (maximize profit, minimize cost) subject to linear constraints. The optimal solution always occurs at a vertex of the feasible region (simplex method).\n\nReal-world applications: airline scheduling, supply chain logistics, portfolio optimization, and machine learning (linear regression minimizes mean squared error).\n\nVector form of a line: r = a + t·d where a is a point, d is the direction vector, and t is a parameter — fundamental in 3D graphics and physics simulations."
  },
  20: {
    additionalInfo: "Vertex form: f(x)=a(x-h)²+k. The vertex is at (h,k) — the minimum if a>0 (opens up), maximum if a<0 (opens down). Axis of symmetry is x=h.\n\nVieta's formulas: for ax²+bx+c=0 with roots r₁ and r₂: r₁+r₂=-b/a and r₁·r₂=c/a. Useful for finding sum and product of roots without solving.\n\nApplications: projectile motion y=-½gt²+v₀t+y₀, area optimization, revenue maximization (revenue = price × quantity).",
    deepDive: "Complex numbers: a+bi where i=√(-1). They form the complex plane (Argand diagram). Multiplication rotates and scales in the complex plane.\n\nThe Fundamental Theorem of Algebra: every polynomial of degree n has exactly n roots (counting multiplicity) in the complex numbers. A quadratic always has exactly 2 roots.\n\nNewton's Method iteratively approximates roots: x_(n+1) = x_n - f(x_n)/f'(x_n). Converges quadratically — very fast. Used in computer graphics and scientific computing."
  },
  21: {
    additionalInfo: "Composition of functions: (f∘g)(x) = f(g(x)) — apply g first, then f. Inverse functions: f⁻¹ undoes f. f(f⁻¹(x))=x. Graphically, inverses are reflections across y=x.\n\nPiecewise functions define different rules for different parts of the domain. Used in tax brackets, shipping rates, and physics.\n\nEven functions: f(-x)=f(x) — symmetric about y-axis (e.g., cos, x²). Odd functions: f(-x)=-f(x) — symmetric about origin (e.g., sin, x³).",
    deepDive: "Trigonometric functions model periodic phenomena: sound waves, alternating current, tides. Unit circle: (cos θ, sin θ) for angle θ. Period of sin/cos: 2π.\n\nFourier Transform decomposes any periodic signal into sines and cosines — the mathematical foundation of MP3 audio compression and JPEG image compression.\n\nBig O notation borrows from mathematical functions: O(1) constant, O(log n) logarithmic, O(n) linear, O(n²) quadratic — essential for algorithm analysis."
  },
  22: {
    additionalInfo: "Outliers significantly affect the mean but not the median. For skewed data (income, home prices), the median is a better typical value. The mean is best when data is symmetric.\n\nBox plots show Q1 (25th percentile), median (50th), Q3 (75th), and outliers. IQR = Q3-Q1; outliers are typically beyond 1.5×IQR from the box.\n\nWeighted mean: w̄ = Σ(wᵢxᵢ)/Σwᵢ. Used in GPA calculation, portfolio returns, and survey analysis.",
    deepDive: "The coefficient of variation (CV = σ/μ) measures relative variability — useful for comparing datasets with different units or magnitudes.\n\nMoments of a distribution: 1st = mean (location), 2nd = variance (spread), 3rd = skewness (asymmetry), 4th = kurtosis (tail thickness). Financial risk analysis uses all four.\n\nData visualization: histograms show frequency distribution, scatter plots show correlation, violin plots combine box plots with density estimation. matplotlib/seaborn (Python) and ggplot2 (R) are standard tools."
  },
  23: {
    additionalInfo: "Bayes' Theorem: P(A|B) = P(B|A)×P(A)/P(B). Used in spam filters, medical diagnosis, and AI. Posterior = likelihood × prior / evidence.\n\nExpected value E(X) = Σ(x·P(x)) — the long-run average of a random variable. Variance Var(X) = E(X²) - [E(X)]². A fair game has E=0.\n\nCombinatorics: permutations (order matters) nPr = n!/(n-r)!; combinations nCr = n!/(r!(n-r)!). Used in poker hand probabilities and genetics.",
    deepDive: "Frequentist vs Bayesian statistics: frequentists interpret probability as long-run frequency; Bayesians as degree of belief updated by evidence. Both have appropriate use cases.\n\nMonte Carlo simulation uses random sampling to estimate probabilities and integrals. Used in finance (option pricing), physics, and AI training.\n\nMarkov chains model systems where the future depends only on the current state (memoryless). Used in Google's PageRank algorithm, language models, and weather forecasting."
  },
  24: {
    additionalInfo: "Z-score = (x-μ)/σ standardizes values, expressing distance from mean in standard deviations. A z-score of 2 means 2 standard deviations above the mean.\n\nCentral Limit Theorem (CLT): the sampling distribution of the mean approaches normal as sample size grows, regardless of the population distribution. Foundation of most inferential statistics.\n\nHypothesis testing: null hypothesis H₀ (no effect), alternative H₁. p-value = probability of data given H₀. p < 0.05 is typically 'statistically significant.'",
    deepDive: "The t-distribution has heavier tails than normal — used when sample size is small (<30) or population σ is unknown. Degrees of freedom control tail weight.\n\nChi-square test assesses whether observed frequencies differ from expected — used for testing independence in contingency tables (e.g., is gender independent of voting preference?).\n\nA/B testing in tech: randomly assign users to A or B, measure conversion rates. Statistical tests determine if the difference is significant. False discovery rate control is essential when testing many variants."
  },
  25: {
    additionalInfo: "SOHCAHTOA: Sin=Opposite/Hypotenuse, Cos=Adjacent/Hypotenuse, Tan=Opposite/Adjacent — the basis of trigonometry and navigation.\n\nSimilar triangles have equal angles and proportional sides. AA (Angle-Angle) similarity: if two angles match, triangles are similar. Used in shadow measurement and map scaling.\n\nThe triangle inequality: any side must be less than the sum of the other two sides. Used in network routing and computational geometry.",
    deepDive: "Euler's formula for polyhedra: V - E + F = 2 (vertices - edges + faces = 2). A tetrahedron: 4-6+4=2. Works for all convex polyhedra.\n\nNon-Euclidean geometry: on a sphere (elliptic geometry), triangle angles sum to MORE than 180°. On a saddle surface (hyperbolic), less than 180°. Einstein's general relativity uses curved spacetime geometry.\n\nDelaunay triangulation divides points into triangles for mesh generation, terrain modeling, and game graphics."
  },
  26: {
    additionalInfo: "Radians: an angle in radians = arc length / radius. 2π radians = 360°. π radians = 180°. Radians simplify calculus — derivative of sin(x) = cos(x) only works in radians.\n\nCircle theorems: angle at center = 2 × angle at circumference for the same arc. Opposite angles in a cyclic quadrilateral sum to 180°.\n\nTangent line: touches the circle at exactly one point, perpendicular to the radius at that point. Used in architecture, optics, and physics.",
    deepDive: "Pi (π) is transcendental — proved by Lindemann in 1882. This means squaring the circle with compass and straightedge is mathematically impossible.\n\nPi has been computed to over 100 trillion digits using the Chudnovsky algorithm. Digits appear statistically random — no pattern has been found.\n\nEuler's identity: e^(iπ) + 1 = 0. Often called 'the most beautiful equation in mathematics' — connecting the five most fundamental constants: e, i, π, 1, 0."
  },
  27: {
    additionalInfo: "Cavalieri's Principle: two solids with equal cross-sectional areas at every height have equal volumes. This is how the sphere volume formula V=(4/3)πr³ is derived.\n\nScaling laws: if you double all dimensions, area scales by 4× and volume by 8×. This explains why larger animals need proportionally thicker bones.\n\nPrisms: V = base area × height. Pyramids: V = (1/3) × base area × height — exactly 1/3 of the corresponding prism.",
    deepDive: "Spherical geometry: great circles (equator and meridians) are the shortest paths on Earth's surface. Latitude/longitude uses spherical coordinates (r, θ, φ).\n\nPolyhedra: the 5 Platonic solids (tetrahedron, cube, octahedron, dodecahedron, icosahedron) are the only perfectly regular convex polyhedra. Kepler tried to model planetary orbits with them.\n\nFractals are self-similar shapes with non-integer (fractal) dimensions. The Mandelbrot set, Sierpinski triangle, and Koch snowflake are famous examples. Fractal geometry models coastlines, clouds, and trees."
  },
  28: {
    additionalInfo: "Friction: static friction prevents motion (up to a maximum), kinetic friction opposes sliding. f=μN where μ is the coefficient of friction and N is the normal force.\n\nCircular motion: centripetal acceleration a=v²/r directed inward. Centripetal force F=mv²/r — not a new force, but whatever force provides inward acceleration (tension, gravity, normal).\n\nTerminal velocity: when air resistance equals gravity, net force = 0, acceleration = 0, and speed becomes constant. Skydivers reach ~55 m/s in spread position.",
    deepDive: "Einstein's Special Relativity (1905): time dilation (moving clocks run slow), length contraction, E=mc². No object with mass can reach the speed of light.\n\nGeneral Relativity (1915): gravity is the curvature of spacetime caused by mass. Confirmed by gravitational waves (LIGO 2015) and black hole imaging (Event Horizon Telescope 2019).\n\nQuantum mechanics governs the subatomic world: Heisenberg's uncertainty principle — you can't simultaneously know exact position and momentum."
  },
  29: {
    additionalInfo: "Elastic PE: PE=½kx² stored in a spring. Chemical PE stored in molecular bonds. Nuclear PE from the strong nuclear force.\n\nThermodynamics: 1st Law — energy is conserved (ΔU=Q-W). 2nd Law — entropy of an isolated system never decreases. 3rd Law — absolute zero (0K) is unattainable.\n\nEfficiency: η = useful output / total input. Carnot efficiency = 1 - T_cold/T_hot — the theoretical maximum for a heat engine.",
    deepDive: "Dark energy (~68% of the universe) is an unknown force accelerating the universe's expansion, discovered in 1998. Dark matter (~27%) provides gravitational effects without emitting light.\n\nThe Higgs boson (discovered 2012 at CERN) is the quantum of the Higgs field that gives fundamental particles their mass.\n\nString theory attempts to unify quantum mechanics and general relativity by modeling particles as vibrating strings in 10 or 11 dimensions. Not yet confirmed experimentally."
  },
  30: {
    additionalInfo: "Doppler effect: moving toward each other increases observed frequency (blueshift). Moving away decreases frequency (redshift). Used in radar guns, weather forecasting, and astronomy.\n\nRefraction: wave bends when changing medium (Snell's law: n₁sinθ₁ = n₂sinθ₂). Total internal reflection traps light in fiber optic cables.\n\nDiffraction: waves spread around obstacles and through slits. Constructive interference adds amplitudes; destructive interference cancels them.",
    deepDive: "Laser (Light Amplification by Stimulated Emission of Radiation) produces coherent, monochromatic light. Used in surgery, fiber optics, manufacturing, and barcode scanners.\n\nQuantum nature of light: photons have energy E=hf (h=Planck's constant). Photoelectric effect (Einstein 1905) proved light has particle properties. Wave-particle duality applies to electrons too.\n\nSuperposition of waves produces standing waves — fundamental to musical instruments, microwave ovens, and quantum mechanics (electrons in orbitals form standing waves)."
  },
  31: {
    additionalInfo: "Electron configuration: electrons fill orbitals in order of increasing energy (Aufbau principle). Orbitals: s(2), p(6), d(10), f(14). Valence electrons determine reactivity.\n\nPeriodic trends: atomic radius decreases across a period (more protons pull electrons in). Electronegativity increases across a period. Ionization energy increases across a period.\n\nIsotopes: Carbon-14 is used in carbon dating. Uranium-235 powers nuclear reactors. Iodine-131 treats thyroid cancer.",
    deepDive: "Quantum model: Bohr's circular orbit model was replaced by quantum mechanical probability clouds. Schrödinger's equation gives the wave function of electrons.\n\nNuclear reactions: fission splits heavy nuclei releasing enormous energy. Fusion joins light nuclei — the power source of stars and future reactors (ITER). Mass converts to energy via E=mc².\n\nThe Standard Model classifies all known fundamental particles: quarks (make up protons/neutrons), leptons (electrons, neutrinos), and bosons (force carriers)."
  },
  32: {
    additionalInfo: "VSEPR theory: electron pairs arrange to minimize repulsion. Water (2 bonds + 2 lone pairs) = bent shape (104.5°), causing polarity. Methane (4 bonds) = tetrahedral (109.5°).\n\nMetallic bonds: electrons delocalized over all metal atoms ('sea of electrons') — explains electrical conductivity, thermal conductivity, and malleability.\n\nIntermolecular forces (weakest to strongest): London dispersion forces, dipole-dipole, hydrogen bonds. These determine boiling and melting points.",
    deepDive: "Molecular orbital (MO) theory treats electrons as delocalized over the entire molecule. Explains bonding in benzene (aromatic compounds) and why O₂ is paramagnetic.\n\nCoordination chemistry: transition metals form complex ions with ligands. Hemoglobin binds O₂ via iron(II). Cisplatin (a platinum complex) is a chemotherapy drug.\n\nPolymers: addition polymers (ethylene → polyethylene). Condensation polymers release water as monomers join (nylon, polyester, DNA, proteins). Materials science depends on polymer chemistry."
  },
  33: {
    additionalInfo: "Reaction rates depend on concentration, temperature, surface area, and catalysts. Arrhenius equation: k = Ae^(-Ea/RT). Higher temperature means more molecules overcome activation energy.\n\nLe Chatelier's Principle: when a system at equilibrium is disturbed, it shifts to counteract the disturbance. Add reactant → shifts right. Increase temperature → shifts toward endothermic direction.\n\npH scale: pH = -log[H⁺]. pH 7 neutral, <7 acidic, >7 basic. Buffer solutions resist pH change.",
    deepDive: "Electrochemistry: galvanic cells convert chemical energy to electrical energy (batteries). Electrolytic cells use electricity to drive non-spontaneous reactions (electroplating, aluminum production).\n\nGibbs free energy: ΔG = ΔH - TΔS. Reaction is spontaneous if ΔG < 0. Combines enthalpy (heat) and entropy (disorder) into one quantity.\n\nGreen chemistry (12 principles): design processes to reduce hazardous substances, minimize waste, use renewable feedstocks, and improve atom economy."
  },
  34: {
    additionalInfo: "Cell cycle: G1 (growth) → S phase (DNA replication) → G2 (preparation) → M phase (mitosis) → cytokinesis. Checkpoints prevent damaged DNA from replicating.\n\nEndosymbiotic theory: mitochondria and chloroplasts were once free-living bacteria that were engulfed. Evidence: own circular DNA, double membrane, own ribosomes.\n\nCell communication: receptor proteins bind signaling molecules (hormones, neurotransmitters). Signal cascades amplify the message inside the cell. Disrupted signaling causes cancer.",
    deepDive: "CRISPR-Cas9: a bacterial immune system repurposed to cut DNA at precise locations. Allows adding, removing, or correcting genes. Applications: genetic disease treatment, crop improvement.\n\nCAR-T cell therapy engineers a patient's own T cells to recognize and kill cancer cells. FDA-approved for some leukemias and lymphomas.\n\nStem cells can differentiate into specialized cell types. Induced pluripotent stem cells (iPSCs, Yamanaka 2006) reprogram adult cells — avoiding ethical concerns. Used in organ-on-a-chip and regenerative medicine."
  },
  35: {
    additionalInfo: "Central dogma: DNA → (transcription) → mRNA → (translation) → protein. Ribosomes read codons (3-base sequences) and add corresponding amino acids.\n\nEpigenetics: gene expression is regulated without changing DNA sequence — via DNA methylation and histone modification. Environment, diet, and stress influence epigenetic marks. Some are heritable.\n\nPCR (Polymerase Chain Reaction) amplifies specific DNA sequences — used in COVID-19 tests, forensics, paternity testing, and ancient DNA analysis.",
    deepDive: "Human genome: ~3 billion base pairs, ~20,000-25,000 protein-coding genes. Only ~1.5% of DNA codes for proteins; the rest includes regulatory regions and non-coding RNA.\n\nGenome-Wide Association Studies (GWAS) scan hundreds of thousands of genetic variants to find associations with diseases and traits. Identified thousands of disease-linked variants.\n\nSynthetic biology designs biological systems from scratch. Companies use cell programming to produce fragrances, medicines, and materials. iGEM competition creates biosensors and biofuels."
  },
  36: {
    additionalInfo: "Modern Synthesis merges Darwin's natural selection with Mendelian genetics. Hardy-Weinberg equilibrium: allele frequencies are stable unless disturbed by selection, mutation, drift, gene flow, or non-random mating.\n\nConvergent evolution: unrelated species evolve similar traits due to similar environments — wings in birds, bats, and insects; streamlined bodies in fish, dolphins, and ichthyosaurs.\n\nHuman evolution: Homo sapiens emerged ~300,000 years ago in Africa. We interbred with Neanderthals — non-African humans carry ~1-4% Neanderthal DNA.",
    deepDive: "Evolutionary medicine: sickle cell disease heterozygotes are more resistant to malaria — balanced polymorphism. Morning sickness may protect the embryo from toxins. Antibiotic resistance is evolution in real time.\n\nExtinction: the K-Pg extinction (66 MYA) wiped out non-avian dinosaurs — caused by an asteroid impact. We are in the 6th mass extinction driven by human activity.\n\nArtificial selection dramatically accelerates evolution. Dogs were domesticated from wolves ~15,000 years ago. GMOs extend selective breeding to genetic engineering."
  },
  37: {
    additionalInfo: "Egyptian calendar: 365 days (12 months of 30 days + 5 extra). The annual Nile flood brought fertile silt — Egyptian agriculture depended on it. Nilometer gauges measured flood levels to predict harvests and taxes.\n\nThree kingdoms: Old Kingdom (pyramids), Middle Kingdom (stability, trade), New Kingdom (expansion, Ramesses II). Intermediate periods saw foreign rule.\n\nEgyptian religion: polytheistic with 2000+ gods. Ra (sun), Osiris (afterlife), Isis (magic), Horus (pharaoh). Mummification preserved the body for resurrection.",
    deepDive: "The Library of Alexandria (~300 BCE) was the ancient world's greatest repository of knowledge — up to 700,000 scrolls on all subjects. It was gradually lost over centuries.\n\nCleopatra VII (51-30 BCE) was the last active pharaoh, fluent in nine languages. She formed alliances with Julius Caesar and Mark Antony before Egypt fell to Rome.\n\nAncient Egyptian mathematics: base-10 system. The Rhind Mathematical Papyrus (1550 BCE) contains 84 math problems including area and volume calculations, and primitive fractions."
  },
  38: {
    additionalInfo: "Athenian democracy was direct — male citizens voted on laws in the Assembly. Only ~10-20% of Athens' population could vote (excluded women, slaves, foreigners).\n\nAlexander the Great (356-323 BCE) conquered territory from Greece to India in 13 years, spreading Greek culture (Hellenism) across the known world.\n\nRoman engineering: concrete, aqueducts, 80,000 km of paved roads, the Colosseum (50,000 seats). Roman law forms the basis of legal systems across Europe and Latin America.",
    deepDive: "The Pax Romana (27 BCE-180 CE): 200+ years of relative peace. Trade flourished along the Silk Road from China to Rome. Population: ~60-70 million.\n\nFall of Rome: military overstretch, economic troubles, political instability, climate change (Roman Climate Optimum ended), barbarian invasions, and disease (Antonine Plague, Plague of Cyprian).\n\nByzantine Empire survived until 1453 CE when Constantinople fell to the Ottoman Turks. Its fall is often used to mark the end of the Middle Ages and the beginning of the Renaissance."
  },
  39: {
    additionalInfo: "Invention timeline from Mesopotamia: writing (~3400 BCE), the wheel (~3500 BCE), the plow, beer brewing, and organized religion with temple complexes (ziggurats).\n\nBabylonian astronomy: tracked planets, predicted eclipses, and divided the day into 24 hours and the circle into 360 degrees — still used today. Their base-60 system gives us 60 seconds and 60 minutes.\n\nThe Epic of Gilgamesh (2100 BCE) is the world's oldest surviving literature — includes a flood narrative predating the Biblical account, themes of friendship, mortality, and immortality.",
    deepDive: "The Akkadian Empire (Sargon of Akkad, ~2334 BCE) was possibly the world's first empire — centralized rule over multiple city-states. Created a standing army and standardized administration.\n\nAssyrian Empire (911-609 BCE): first to systematically use iron weapons, cavalry, and siege warfare. The Nineveh library (Ashurbanipal) preserved thousands of clay tablet texts.\n\nNeo-Babylonian: Nebuchadnezzar II built the Ishtar Gate and possibly the Hanging Gardens. Conquered Jerusalem and destroyed Solomon's Temple (586 BCE), beginning the Babylonian Captivity."
  },
  40: {
    additionalInfo: "The Schlieffen Plan: Germany planned to quickly defeat France through Belgium, then face Russia. It failed — Belgium resisted, Britain entered, France held. Result: years of trench warfare.\n\nNew technologies in WWI: machine guns, poison gas (chlorine, mustard gas), tanks (introduced 1916), aircraft, submarines (U-boats). The war demonstrated that modern industry had made warfare catastrophically lethal.\n\nRussian Revolution (1917): war exhaustion and food shortages led to the fall of Tsar Nicholas II. Bolsheviks (Lenin) seized power in October; Russia withdrew from WWI via the Treaty of Brest-Litovsk.",
    deepDive: "The Spanish Flu (1918-1919) killed 50-100 million worldwide — more than WWI itself. Soldiers spread it globally. It disproportionately killed young adults, possibly due to a 'cytokine storm' immune response.\n\nWilson's Fourteen Points (1918) included self-determination, open diplomacy, free seas, and a League of Nations (precursor to the UN). The Treaty of Versailles incorporated little of it.\n\nThe 'war guilt clause' (Article 231) forced Germany to accept blame for WWI and pay massive reparations (~$33 billion). This economic devastation and national humiliation fueled the rise of Nazism."
  },
  41: {
    additionalInfo: "Blitzkrieg ('lightning war'): Germany's fast combined-arms strategy — tanks, motorized infantry, and airpower. Overwhelmed France in 6 weeks (May-June 1940) despite a larger Allied force.\n\nBattle of Britain (1940): Germany attempted to destroy the RAF to enable invasion. Britain won, aided by radar (Chain Home) and Ultra — code-breaking Enigma using Turing's Bombe machines at Bletchley Park.\n\nOperation Barbarossa (June 1941): Germany invaded the USSR — the largest military operation in history. Stalingrad (1942-43) encircled 300,000 Axis troops. The Eastern Front caused ~80% of all German military deaths.",
    deepDive: "The Manhattan Project (1942-1945): the US, UK, and Canada secretly developed the atomic bomb, employing 130,000 people. Two bombs dropped on Hiroshima and Nagasaki killed 130,000-226,000 people and ended the war.\n\nNuremberg Trials (1945-1946): senior Nazi leaders tried for war crimes and crimes against humanity. Established the precedent of individual responsibility under international law. 12 sentenced to death.\n\nThe UN was founded October 24, 1945. The Universal Declaration of Human Rights (1948) emerged from post-war reflection. Decolonization accelerated as European powers were weakened."
  },
  42: {
    additionalInfo: "Marshall Plan (1948): the US provided $13 billion to rebuild war-damaged Western Europe, preventing economic collapse that might have led to communist revolutions. NATO founded 1949; Warsaw Pact 1955.\n\nSpace Race: Sputnik (1957) shocked the West. Yuri Gagarin (1961) — first human in space. Apollo 11 (July 20, 1969) — Neil Armstrong on the Moon. Drove rapid advances in computing and materials.\n\nProxy wars: Korean War (1950-53), Vietnam War (1955-75), Soviet-Afghan War (1979-89). Millions died in these conflicts without direct US-USSR combat.",
    deepDive: "Détente (1970s): reduced tensions. Nixon's 1972 visit to China drove a wedge between China and USSR. SALT treaties limited nuclear weapons. Nixon-Brezhnev summits.\n\nReagan Doctrine (1980s): support anti-communist movements worldwide. Increased defense spending, Strategic Defense Initiative ('Star Wars'). Soviet economy couldn't keep up.\n\nCollapse of the USSR: Gorbachev's glasnost and perestroika reforms loosened control. Eastern Bloc countries broke free in 1989 (Velvet Revolution). Soviet republics declared independence. USSR dissolved December 25, 1991."
  },
  43: {
    additionalInfo: "Global poverty: extreme poverty (<$2.15/day) fell from 36% (1990) to ~9% (2022) — largely due to China's rise and economic integration. COVID-19 pandemic reversed some progress.\n\nSupply chains: modern products involve components from dozens of countries. A smartphone contains minerals from Congo, chips from Taiwan, assembled in China. COVID-19 revealed supply chain fragility.\n\nDeglobalization trends: trade wars (US-China tariffs), Brexit, and geopolitical tensions are pushing companies to nearshore production.",
    deepDive: "The Washington Consensus (1989): fiscal discipline, privatization, deregulation, trade liberalization — advocated by IMF and World Bank for developing countries. Implemented with mixed results.\n\nChinese economic miracle: GDP grew from $305 billion (1980) to $18 trillion (2023) — the fastest sustained growth for a large economy. Now the world's #1 trading nation and #2 economy.\n\nDigital divide: global internet penetration is ~65% (2023). Access varies dramatically — 93% in Europe vs ~40% in Sub-Saharan Africa. Closing this gap is essential for economic development and education access."
  },
  44: {
    additionalInfo: "ARPANET (1969): the precursor to the internet. TCP/IP protocol standardized in 1983. DNS in 1985. The internet predates the Web — the internet is the network infrastructure; the Web is an application running on it.\n\nSocial media timeline: MySpace (2003), Facebook (2004), YouTube (2005), Twitter (2006), iPhone App Store (2008), Instagram (2010), TikTok (2016). Billions of hours used daily.\n\nCryptocurrency: Bitcoin (2009, Satoshi Nakamoto) introduced blockchain — a decentralized, immutable ledger. Ethereum added smart contracts. Crypto remains controversial: financial inclusion vs. energy use and volatility.",
    deepDive: "AI milestones: Deep Blue beat Kasparov in chess (1997). AlphaGo beat the world Go champion (2016) — considered impossible for AI just years before. ChatGPT (2022) brought large language models to mass awareness.\n\nThe attention economy: social media algorithms amplify emotionally triggering content to maximize engagement. Implications for political polarization, misinformation, and teen mental health are widely studied.\n\nDigital governance challenges: who controls the internet? Content moderation at scale is technically and politically complex. Data sovereignty, antitrust, and AI regulation are hotly debated policy areas globally."
  },
  45: {
    additionalInfo: "Carbon budget: to limit warming to 1.5°C, we can emit ~380 Gt CO₂ more (as of 2023). At current rates, this budget is exhausted in ~8-9 years. Net zero by 2050 is the widely agreed target.\n\nTipping points: self-reinforcing processes — Amazon dieback, permafrost methane release, West Antarctic Ice Sheet collapse. Some may already be triggered. Highly irreversible changes.\n\nEnergy transition: solar and wind are now the cheapest new electricity sources in most of the world. Global renewable capacity is growing rapidly. Electric vehicles are becoming mainstream.",
    deepDive: "Carbon capture and storage (CCS): capturing CO₂ from power plants or air (Direct Air Capture) and storing underground. Currently expensive and small-scale. Considered essential in most IPCC net-zero scenarios.\n\nClimate justice: developing countries contributed least to historical emissions but face the greatest impacts (sea level rise, droughts, extreme heat). Climate finance — wealthy nations promised $100B/year — remains largely unfulfilled.\n\nIPCC 6th Assessment Report (2021-2023): 'unequivocal' human influence, 'code red for humanity.' 1.1°C warming already observed. Limiting to 1.5°C requires rapid, deep, and immediate emissions cuts across all sectors."
  },
  46: {
    additionalInfo: "Nouns: proper (London, Maria) vs common (city, girl). Count (one apple, three apples) vs mass/uncountable (water, furniture, advice). Collective (team, flock, jury).\n\nVerbs: transitive (takes a direct object: 'She reads books') vs intransitive ('He sleeps'). Linking verbs (be, seem, become, feel) connect subject to a complement: 'The soup tastes good.'\n\nConjunctions: coordinating (FANBOYS: for, and, nor, but, or, yet, so). Subordinating (although, because, while). Correlative (either...or, not only...but also).",
    deepDive: "Gerunds (verb+ing as noun): 'Swimming is fun.' Infinitives (to+verb): 'She likes to run.' Participles (verb form as adjective): 'The running water,' 'the broken window.'\n\nDangling modifiers: 'Running to catch the bus, the rain started.' (The rain wasn't running!) Fix: 'Running to catch the bus, he got soaked in the rain.'\n\nEnglish is a Germanic language heavily influenced by French (Norman Conquest 1066) and Latin. About 60% of English vocabulary is French or Latin in origin — which is why English has pairs like 'ask' (Germanic) and 'inquire' (Latin)."
  },
  47: {
    additionalInfo: "English has 12 tenses (4 aspects × 3 time frames). Aspect shows whether an action is simple, continuing, or completed. The perfect aspect always uses 'have/has/had + past participle.'\n\nConditionals: Zero (scientific truths: 'Water boils at 100°C if heated'). First (real future). Second (hypothetical: 'If I won, I would travel'). Third (past hypothetical: 'If I had studied, I would have passed').\n\nAmerican vs British English: 'Did you eat?' (AmE) vs 'Have you eaten?' (BrE) for recent events. BrE uses present perfect more for recent past.",
    deepDive: "The passive voice shifts focus to the receiver: 'The Mona Lisa was painted by Leonardo.' Useful when the agent is unknown, unimportant, or obvious.\n\nReported (indirect) speech shifts tense back: 'I am tired' → 'She said she was tired.' Modal changes: 'I can' → 'She said she could.' Pronouns shift: 'I' → 'she/he.'\n\nAspect systems differ across languages: Russian has perfective/imperfective as a grammatical category. Mandarin uses particles to indicate aspect. English aspect is conveyed through auxiliary verbs."
  },
  48: {
    additionalInfo: "Oxford comma (serial comma): the comma before 'and' in a list — 'red, white, and blue.' American English typically includes it; British English often omits it. Famous ambiguous example: 'To my parents, Ayn Rand and God.'\n\nHyphen vs en dash vs em dash: hyphen (-) for compound words. En dash (–) for ranges (2010–2020). Em dash (—) for emphasis — like this. Usage varies between style guides.\n\nParentheses add non-essential information. Brackets add editorial clarification inside quotations. Ellipsis (...) indicates omitted text or trailing off.",
    deepDive: "Punctuation in other languages: French puts spaces before ! ? : ; — 'Bonjour !' Spanish uses inverted opening punctuation: ¿Pregunta? and ¡Exclamación! German capitalizes all nouns, making capitalization a grammatical feature.\n\nEvolution of punctuation: Greek and Latin texts had no spaces between words and no punctuation. Word spaces appeared in the 7th century CE. Modern punctuation developed gradually with the printing press (Gutenberg, 1440s).\n\nDigital communication has evolved punctuation norms: a period at the end of a text message can now signal formality or passive aggression. Emoji have become new punctuation-like signals in informal communication."
  },
  49: {
    additionalInfo: "Formal vs informal: use 'usted' (Ud.) with strangers, elders, and professionals. Use 'tú' with friends and family. '¿Cómo está usted?' is formal; '¿Cómo estás?' is informal.\n\nSpanish uses inverted opening punctuation: ¡Hola! ¿Cómo estás? This helps readers prepare for tone before reaching the end of a long sentence.\n\nAccents change meaning: sí (yes) vs si (if); él (he) vs el (the); más (more) vs mas (but).",
    deepDive: "Spanish is spoken by 580+ million native speakers — 2nd most spoken language by natives after Mandarin. 20+ countries use it as an official language.\n\nRegional varieties: Castilian (Spain) pronounces 'c' before e/i and 'z' as 'th.' Latin American Spanish pronounces these as 's' (seseo). Vocabulary also differs: 'coche' (Spain) vs 'carro' (Latin America) for car.\n\nFalse friends (cognados falsos): 'embarazada' means pregnant, not embarrassed. 'Sensible' means sensitive. 'Actualmente' means currently, not actually."
  },
  50: {
    additionalInfo: "Numbers 11-20 are irregular: once, doce, trece, catorce, quince, dieciséis, diecisiete, dieciocho, diecinueve, veinte. From 31 onward: treinta y uno, etc. Hundreds: cien (100), doscientos, trescientos...\n\nMasculine nouns typically end in -o (libro/book), feminine in -a (mesa/table). Exceptions: el mapa (masculine despite -a), la mano (feminine despite -o). Nouns ending in -ción, -sión, -dad are feminine.\n\nAdjective placement: most Spanish adjectives follow the noun (casa grande). Some change meaning: 'un gran hombre' (a great man) vs 'un hombre grande' (a big man).",
    deepDive: "Ordinal numbers: primero, segundo, tercero, cuarto, quinto, sexto, séptimo, octavo, noveno, décimo. Shortened before masculine singular: primer (first), tercer (third).\n\nTime in Spanish: ¿Qué hora es? Son las tres y media (3:30). Es la una (1:00 — singular 'la'). Son las cuatro menos cuarto (3:45).\n\nCurrency: Spain uses Euro (€). Most Latin American countries use their own currencies (Mexican Peso, Colombian Peso, Chilean Peso). The US Dollar is official in Ecuador, El Salvador, and Panama."
  },
  51: {
    additionalInfo: "Stem-changing verbs change their stem vowel in all forms EXCEPT nosotros/vosotros: e→ie (querer: quiero, quieres, quiere...), o→ue (poder: puedo), e→i (pedir: pido).\n\nReflexive verbs with pronouns (me, te, se, nos, os, se): levantarse (to get up) — yo me levanto. Used when subject acts on itself: ducharse (to shower), llamarse (to be called).\n\nSer vs Estar extended: Ser for DOCTOR (Description, Occupation, Characteristics, Time, Origin, Relationships). Estar for PLACE (Position, Location, Action, Condition, Emotion).",
    deepDive: "Subject pronouns (yo, tú, él, ella, usted...) are often omitted because verb endings indicate the subject. 'Hablo' alone means 'I speak.' Pronoun inclusion adds emphasis or contrast.\n\nVosotros is used only in Spain for informal plural 'you.' Latin America uses 'ustedes' for both formal and informal plural — one of the biggest differences between Castilian and Latin American Spanish.\n\nPresent tense can express: current actions ('Hablo español'), habitual actions ('Como a las 8'), future plans ('Mañana viajo a Madrid'), and historical present for vivid narration."
  },
  52: {
    additionalInfo: "The PEEL paragraph structure: Point (topic sentence), Evidence (quote or data), Explain (analysis), Link (back to thesis). Ensures every paragraph is purposeful and connected to the argument.\n\nCounterarguments strengthen essays: acknowledge the opposing view (concede), then rebut it with stronger evidence. Shows intellectual honesty and makes your argument more persuasive.\n\nHook types: surprising statistic, provocative question, anecdote, paradox, or vivid description. Match the hook to the essay's tone.",
    deepDive: "Academic citation styles: MLA (humanities), APA (social sciences, psychology), Chicago/Turabian (history, arts). Each has specific formats for in-text citations and reference lists/bibliographies.\n\nPlagiarism: using others' ideas or words without attribution. Paraphrasing without credit is also plagiarism. AI-generated text without disclosure is a growing academic concern.\n\nExtended essays require original research. Literature reviews synthesize existing research. Methodology sections explain how data was gathered. Discussion sections interpret findings in context of existing research."
  },
  53: {
    additionalInfo: "Wordiness to avoid: 'due to the fact that' → 'because'; 'in the event that' → 'if'; 'at this point in time' → 'now'; 'in order to' → 'to'. Remove empty phrases that add no meaning.\n\nSentence variety: combine short sentences to show relationship ('It rained. We stayed inside.' → 'Because it rained, we stayed inside.'). Break up long sentences. Aim for 15-20 words on average.\n\nThe Gunning fog index: readability score = 0.4 × (words/sentences + % long words). Aim for score ≤12 for general audiences.",
    deepDive: "George Orwell's six rules for clear writing (1946, 'Politics and the English Language'): Never use a long word where a short one will do. If it is possible to cut a word out, always cut it out. Never use passive where you can use active. Prefer Anglo-Saxon words to Latin or Greek.\n\nScientific writing: IMRAD structure (Introduction, Methods, Results, And Discussion). Passive voice is traditionally used in methods ('Samples were collected...') to emphasize the process.\n\nLegal writing often suffers from 'legalese' — complex sentence structure and archaic terms (whereas, hereinafter). Plain English movements push for more readable legal documents."
  },
  54: {
    additionalInfo: "Logical fallacies weaken arguments: ad hominem (attacking the person), straw man (misrepresenting the opponent's view), false dichotomy (only two options), slippery slope (unwarranted chain of consequences), appeal to authority.\n\nThe Rogerian argument: begin by acknowledging the validity of the opposing view before presenting your own. Creates common ground for highly divisive topics.\n\nNarrative persuasion: stories are more persuasive than statistics alone. Emotional absorption in a story reduces counter-arguing. Pair data with a compelling human story for maximum impact.",
    deepDive: "Propaganda vs persuasion: propaganda uses emotional manipulation, selective truth, and repetition to bypass critical thinking. Advertising techniques: bandwagon, fear appeal, testimonial, scarcity ('limited time offer'), social proof.\n\nDebate formats: Oxford, parliamentary, Lincoln-Douglas (value debates), Policy debate (evidence-intensive). Competitive debate improves critical thinking, research, public speaking, and rebuttal skills.\n\nRhetorical devices: MLK's 'I Have a Dream' used anaphora (repeated phrase) for rhythm and emotional power. Other devices: alliteration, metaphor, repetition, antithesis (opposites in parallel), chiasmus ('Ask not what your country can do for you...')."
  }
};

module.exports = lessonsAdditional;
