require('dotenv').config();
const mongoose = require('mongoose');
const Category = require('./models/Category');
const Game = require('./models/Game');
const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/learningapp';

function lesson(id, subId, order, title, content, questions, flashcards) {
  return { _id: id, order, title, content,
    quiz: { questions: questions.map(([text, options, correctIndex, explanation]) => ({ text, options, correctIndex, explanation })) },
    flashcards: flashcards.map(([front, back]) => ({ front, back }))
  };
}

const categories = [
  { _id: 1, name: 'IT', icon: '💻', color: '#000000',
    description: 'Information technology, operating systems, networking and cybersecurity.',
    subcategories: [
      { _id: 1, name: 'Computer Basics', description: 'How computers work.',
        lessons: [
          lesson(1,1,1,'What is a Computer?',
            'A computer is an electronic device that processes data. It consists of hardware (CPU, RAM, storage, I/O devices) and software (OS, applications).\n\nThe CPU executes instructions. RAM holds data in use. Storage (HDD/SSD) keeps data permanently. Input devices feed data in; output devices display results.',
            [['What does CPU stand for?',['Central Processing Unit','Central Power Unit','Computer Processing Unit','Core Utility'],0,'CPU = Central Processing Unit — the brain of the computer.'],
             ['Which stores data temporarily?',['HDD','SSD','RAM','ROM'],2,'RAM is volatile memory used by the CPU for active data.'],
             ['Which is an input device?',['Monitor','Speaker','Printer','Keyboard'],3,'A keyboard sends data to the computer.']],
            [['CPU','Central Processing Unit — executes instructions.'],['RAM','Fast volatile memory for active data.'],['SSD','Solid State Drive — fast non-volatile storage.'],['I/O','Input/Output — how a computer communicates with users.']]),
          lesson(2,1,2,'Operating Systems',
            'An OS manages hardware and provides a platform for apps. Popular OSes: Windows, macOS, Linux.\n\nThe kernel is the OS core managing hardware. Key concepts: multitasking, file permissions, virtual memory.',
            [['The core component of an OS is?',['Shell','Kernel','Driver','Daemon'],1,'The kernel directly manages hardware resources.'],
             ['Which OS is open-source?',['Windows','macOS','Linux','iOS'],2,'Linux is open-source and freely available.'],
             ['Virtual memory uses?',['GPU','Cloud','Disk as extra RAM','ROM'],2,'Virtual memory extends RAM using disk space.']],
            [['Operating System','Software managing hardware and providing services to apps.'],['Kernel','Core OS component controlling hardware.'],['Multitasking','Running multiple processes simultaneously.'],['Virtual Memory','Disk space used as an extension of RAM.']]),
          lesson(3,1,3,'Computer Networks',
            'A network connects computers to share data. LAN covers a small area; WAN spans large distances.\n\nData travels as packets. IP addresses identify devices. Protocols define rules: HTTP, SMTP, FTP.',
            [['LAN stands for?',['Large Area Network','Local Area Network','Linked Access Node','Logical Address Node'],1,'LAN = Local Area Network.'],
             ['What identifies a device on a network?',['MAC only','IP only','Both','Neither'],2,'IP = logical address; MAC = hardware address.'],
             ['Protocol used for web pages?',['FTP','SMTP','HTTP','SSH'],2,'HTTP transfers web pages.']],
            [['IP Address','Logical network identifier (e.g. 192.168.1.1).'],['MAC Address','Hardware identifier on a network interface card.'],['Packet','Small chunk of data sent across a network.'],['HTTP','HyperText Transfer Protocol — loads web pages.']]),
        ]},
      { _id: 2, name: 'Cybersecurity', description: 'Protect systems and data.',
        lessons: [
          lesson(4,2,1,'Intro to Cybersecurity',
            'Cybersecurity protects systems and data. CIA Triad: Confidentiality, Integrity, Availability.\n\nThreats: malware, phishing, DDoS. Defenses: firewalls, antivirus, IDS, encryption.',
            [['"I" in CIA Triad?',['Intelligence','Integrity','Isolation','Integration'],1,'Integrity = data is not tampered with.'],
             ['What is phishing?',['Port scanning','Tricking users for credentials','Encrypting files for ransom','Flooding a server'],1,'Phishing uses deceptive messages to steal credentials.'],
             ['A firewall?',['Encrypts data','Filters network traffic','Detects viruses','Backs up data'],1,'Firewalls filter network traffic by rules.']],
            [['CIA Triad','Confidentiality, Integrity, Availability.'],['Malware','Malicious software damaging or accessing systems.'],['Phishing','Deceptive attack to steal sensitive info.'],['Firewall','Controls network traffic based on rules.']]),
          lesson(5,2,2,'Encryption & Passwords',
            'Encryption converts plaintext to ciphertext. AES = symmetric (one key). RSA = asymmetric (public/private) — basis for HTTPS.\n\nStrong passwords: 12+ chars, mixed types. Use a password manager. 2FA adds a second verification step.',
            [['Which algorithm is symmetric?',['RSA','ECC','AES','Diffie-Hellman'],2,'AES uses the same key for encrypt and decrypt.'],
             ['HTTPS uses?',['Symmetric only','Asymmetric only','Both','Neither'],2,'HTTPS uses asymmetric for key exchange, symmetric for data.'],
             ['2FA stands for?',['Two firewalls','Two-factor authentication','Two-file archive','Dual frequency'],1,'2FA = Two-Factor Authentication.']],
            [['Encryption','Transforms plaintext to ciphertext using a key.'],['AES','Symmetric cipher widely used today.'],['RSA','Asymmetric algorithm: public encrypts, private decrypts.'],['2FA','Two-Factor Authentication — second proof of identity.']]),
          lesson(6,2,3,'Network Security',
            'VPNs encrypt traffic between device and server. SSL/TLS secures internet communication (browser padlock).\n\nAttacks: Man-in-the-Middle (intercepts traffic), SQL Injection (exploits databases). Penetration testing finds vulnerabilities ethically.',
            [['VPN stands for?',['Virtual Private Network','Very Protected Node','Verified Protocol Network','Virtual Proxy Node'],0,'VPN = Virtual Private Network.'],
             ['Browser padlock means?',['Strong password','SSL/TLS active','Government site','Ad-blocker'],1,'Padlock = SSL/TLS encryption is active.'],
             ['SQL Injection does?',['Overloads a server','Steals cookies','Injects SQL into inputs','Encrypts a database'],2,'SQL injection attacks databases through malicious input.']],
            [['VPN','Encrypts and tunnels internet traffic.'],['SSL/TLS','Protocols for encrypted internet communication.'],['Man-in-the-Middle','Attack intercepting communication between two parties.'],['Pen Testing','Authorized simulated attack to find vulnerabilities.']]),
        ]},
      { _id: 3, name: 'Networking', description: 'Protocols, hardware, and architecture.',
        lessons: [
          lesson(7,3,1,'The OSI Model',
            'OSI has 7 layers: 1-Physical, 2-Data Link, 3-Network (IP), 4-Transport (TCP/UDP), 5-Session, 6-Presentation, 7-Application (HTTP, DNS).\n\nMnemonic: "Please Do Not Throw Sausage Pizza Away".',
            [['IP routing occurs at layer?',['2','3','4','5'],1,'IP is at Layer 3 — the Network layer.'],
             ['TCP operates at layer?',['3','4','5','6'],1,'TCP is Layer 4 — Transport.'],
             ['Physical bit transmission at?',['1','2','3','7'],0,'Layer 1 (Physical) transmits raw bits.']],
            [['OSI Model','7-layer framework for network communication.'],['Layer 3','Network layer — IP addressing and routing.'],['TCP','Reliable transport protocol at Layer 4.'],['DNS','Domain Name System — resolves names to IPs (Layer 7).']]),
          lesson(8,3,2,'TCP vs UDP',
            'TCP: reliable, ordered, connection-oriented. Three-way handshake: SYN→SYN-ACK→ACK. Used for HTTP, email, files.\n\nUDP: connectionless, fast, no guarantee. Used for streaming, gaming, DNS, VoIP.',
            [['Which protocol guarantees delivery?',['UDP','TCP','IP','ICMP'],1,'TCP guarantees reliable, ordered delivery.'],
             ['TCP handshake is?',['GET-POST-PUT','SYN-SYN/ACK-ACK','OPEN-SEND-CLOSE','HELLO-BYE'],1,'SYN→SYN-ACK→ACK establishes a TCP connection.'],
             ['UDP best for?',['Banking','File downloads','Live video streaming','Email'],2,'UDP low overhead suits real-time streaming.']],
            [['TCP','Reliable, connection-oriented protocol with handshaking.'],['UDP','Fast, connectionless protocol; no delivery guarantee.'],['Three-Way Handshake','SYN → SYN-ACK → ACK: establishes TCP connection.'],['Port','Number identifying a process/service (e.g. 80=HTTP).']]),
          lesson(9,3,3,'DNS and HTTP',
            'DNS translates domain names to IP addresses. Your browser queries DNS, then connects to the IP over TCP.\n\nHTTP methods: GET, POST, PUT, DELETE. Status codes: 200 OK, 404 Not Found, 500 Server Error.',
            [['DNS does?',['Encrypts traffic','Translates domains to IPs','Routes packets','Assigns MACs'],1,'DNS resolves domain names to IPs.'],
             ['HTTP method to retrieve data?',['POST','PUT','DELETE','GET'],3,'GET retrieves a resource.'],
             ['HTTP 404 means?',['Server error','Unauthorized','Not Found','OK'],2,'404 = resource not found.']],
            [['DNS','Translates domain names to IP addresses.'],['HTTP GET','Retrieves a resource from a server.'],['HTTP POST','Submits data to a server.'],['Status 200','HTTP OK — request succeeded.']]),
        ]},
    ]},
  { _id: 2, name: 'Programming', icon: '⌨️', color: '#111111',
    description: 'Code from basics to advanced patterns.',
    subcategories: [
      { _id: 4, name: 'Python Fundamentals', description: 'Start with Python.',
        lessons: [
          lesson(10,4,1,'Variables & Data Types',
            'Python is dynamically typed. Types: int, float, str, bool. Collections: list (mutable), tuple (immutable), set (unique), dict (key-value).',
            [['Which is mutable?',['Tuple','String','List','Integer'],2,'Lists are mutable; tuples/strings are not.'],
             ['type(42) returns?',["<class 'str'>","<class 'float'>","<class 'int'>","<class 'num'>"],2,"42 is int."],
             ['Stores unique values only?',['List','Tuple','Dict','Set'],3,'Sets discard duplicates.']],
            [['List','Ordered, mutable: [1, 2, 3]'],['Tuple','Ordered, immutable: (1, 2, 3)'],['Dictionary','Key-value pairs: {"a": 1}'],['Set','Unordered unique values: {1, 2, 3}']]),
          lesson(11,4,2,'Control Flow',
            'Python uses indentation for blocks. if/elif/else for conditions. for/while for loops. break exits, continue skips, pass is no-op.\n\nList comprehension: [x**2 for x in range(10)]',
            [['Exits a loop immediately?',['exit','stop','break','pass'],2,'break exits the loop.'],
             ['Skips to next iteration?',['next','skip','break','continue'],3,'continue skips current iteration.'],
             ['range(3) produces?',['[1,2,3]','[0,1,2,3]','[0,1,2]','[1,2]'],2,'range(3) = 0,1,2.']],
            [['for loop','Iterates over a sequence.'],['while loop','Repeats while condition is True.'],['List Comprehension','[expr for item in iterable if cond]'],['range()','Generates a sequence of numbers.']]),
          lesson(12,4,3,'Functions & Modules',
            'Functions use def. Default params, *args (extra positional), **kwargs (keyword args). Import with import math or from math import sqrt.',
            [['Keyword defining a function?',['function','fun','define','def'],3,'def defines functions in Python.'],
             ['*args collects?',['Keyword args','Extra positional args','Module args','Return values'],1,'*args packs extra positional args into a tuple.'],
             ['Import just sqrt?',['import sqrt from math','from math import sqrt','import math.sqrt','require("math").sqrt'],1,'from math import sqrt is correct.']],
            [['def','Defines a function.'],['return','Sends a value back from a function.'],['*args','Extra positional args as a tuple.'],['**kwargs','Extra keyword args as a dict.']]),
        ]},
      { _id: 5, name: 'JavaScript', description: 'Language of the web.',
        lessons: [
          lesson(13,5,1,'JavaScript Basics',
            'JS is dynamically typed. Declare with let (block, mutable), const (block, immutable), var (function, legacy). Template literals use backticks: `Hello ${name}`.',
            [['Block-scoped, not reassignable?',['var','let','const','function'],2,'const is block-scoped and cannot be reassigned.'],
             ['typeof null returns?',['"null"','"undefined"','"object"','"boolean"'],2,'typeof null === "object" is a JS quirk.'],
             ['Template literal uses?',['"text"',"'text'",'`text`','#text'],2,'Backticks create template literals.']],
            [['let','Block-scoped, reassignable.'],['const','Block-scoped, not reassignable.'],['Template Literal','`Hello ${name}` — string interpolation.'],['undefined','Variable declared but not assigned.']]),
          lesson(14,5,2,'Functions & Scope',
            'Function types: declaration, expression, arrow (const f = (a,b) => a+b). Closure: function remembering outer scope. JS looks up variables from inner to outer scope.',
            [['Arrow function syntax?',['() => {}','function(){}','def()','lambda()'],0,'Arrow functions use => syntax.'],
             ['Closure is?',['No-param function','Function remembering outer scope','IIFE','Callback'],1,'A closure retains access to its lexical scope.'],
             ['Arrow functions bind own "this"?',['Yes','No','Depends','Only strict mode'],1,'Arrow functions inherit "this" from surrounding scope.']],
            [['Arrow Function','const fn = (a,b) => a+b — no own "this".'],['Closure','Function retaining access to outer scope.'],['Hoisting','Function declarations move to top of scope.'],['IIFE','Immediately Invoked Function: (() => {})()']]),
          lesson(15,5,3,'Async JavaScript',
            'JS is single-threaded with an event loop. Callbacks → Promises → async/await.\n\nfetch() returns a Promise. async functions use await to pause for Promises.',
            [['async/await operates on?',['Callbacks','Observables','Promises','Generators'],2,'async/await is sugar over Promises.'],
             ['fetch() returns?',['String','Array','Promise','Callback'],2,'fetch returns a Promise resolving to a Response.'],
             ['Microtasks processed?',['Before call stack','After call stack','In setTimeout','In Worker'],1,'Microtasks run after the current call stack empties.']],
            [['Promise','Future value: .then()/.catch().'],['async/await','Async code that reads like sync code.'],['Event Loop','Processes call stack and task queues.'],['fetch()','Browser API for HTTP requests; returns Promise.']]),
        ]},
      { _id: 6, name: 'Data Structures', description: 'Core structures every dev must know.',
        lessons: [
          lesson(16,6,1,'Arrays & Linked Lists',
            'Array: contiguous memory, O(1) random access, O(n) insert/delete. Linked list: nodes with data+pointer, O(1) head insert, O(n) search.',
            [['Array random access?',['O(n)','O(log n)','O(1)','O(n²)'],2,'Arrays support O(1) index access.'],
             ['Linked list node contains?',['An index','Data + next pointer','Array element','Key-value'],1,'A node has data and a pointer to the next node.'],
             ['Inserting at linked list head?',['O(n)','O(log n)','O(n²)','O(1)'],3,'Head insert only updates the head pointer — O(1).']],
            [['Array','Contiguous memory; O(1) access, O(n) mid-insert.'],['Linked List','Nodes with data+next; O(1) head, O(n) search.'],['O(1)','Constant time — independent of input size.'],['O(n)','Linear time — grows with input size.']]),
          lesson(17,6,2,'Stacks & Queues',
            'Stack: LIFO — push/pop. Used in: call stack, undo, parsing. Queue: FIFO — enqueue/dequeue. Used in: BFS, scheduling. Both O(1) operations.',
            [['LIFO stands for?',['Last In First Out','Last Index From Origin','Linear Input Output','List Index Output'],0,'LIFO = Last In, First Out.'],
             ['BFS uses?',['Stack','Heap','Queue','Tree'],2,'BFS processes nodes with a queue.'],
             ['Call stack uses?',['Queue','Stack','Heap','Graph'],1,'Function calls are pushed/popped from a stack.']],
            [['Stack','LIFO: push adds top, pop removes top.'],['Queue','FIFO: enqueue back, dequeue front.'],['LIFO','Last In, First Out — stack principle.'],['FIFO','First In, First Out — queue principle.']]),
          lesson(18,6,3,'Hash Tables & Trees',
            'Hash table: key→value via hash function. O(1) avg get/set. Collisions handled by chaining or open addressing.\n\nBST: left<node<right. O(log n) avg, O(n) worst. Balanced trees guarantee O(log n).',
            [['Hash table lookup avg?',['O(n)','O(log n)','O(1)','O(n log n)'],2,'Well-designed hash tables provide O(1) avg lookup.'],
             ['BST smaller values go?',['Right','Left','Root','Random'],1,'BST: left subtree holds smaller values.'],
             ['Hash collision occurs when?',['Two identical values','Two keys → same slot','Null key','Empty table'],1,'Collision: two different keys produce same hash index.']],
            [['Hash Table','Key-value store; O(1) avg operations.'],['BST','Binary Search Tree: left<node<right.'],['Hash Collision','Two keys mapping to same bucket.'],['Balanced Tree','Heights differ ≤1; guarantees O(log n).']]),
        ]},
    ]},
  { _id: 3, name: 'Mathematics', icon: '📐', color: '#222222',
    description: 'Algebra, geometry, statistics and the logic behind numbers.',
    subcategories: [
      { _id: 7, name: 'Algebra', description: 'Equations and functions.',
        lessons: [
          lesson(19,7,1,'Linear Equations',
            'Linear equations: degree 1. y=mx+b (slope m, y-intercept b). Solve by isolating the variable. Systems solved by substitution or elimination.',
            [['In y=mx+b, m is?',['y-intercept','x value','Slope','Constant'],2,'m = slope — steepness of the line.'],
             ['Solve: 3x=15',['x=3','x=5','x=45','x=12'],1,'3x=15 → x=5.'],
             ['Linear equations have degree?',['0','1','2','3'],1,'Linear = degree 1.']],
            [['Slope','Rise/run = (y₂-y₁)/(x₂-x₁).'],['y-intercept','Where line crosses y-axis (x=0).'],['Linear Equation','Graph is a straight line; degree 1.'],['System of Equations','Two+ equations solved simultaneously.']]),
          lesson(20,7,2,'Quadratic Equations',
            'Quadratic: ax²+bx+c=0. Solve by factoring, quadratic formula x=(-b±√(b²-4ac))/2a, or completing the square. Discriminant b²-4ac: >0 two real, =0 one real, <0 complex.',
            [['Quadratic formula denominator?',['a','2a','b','2b'],1,'x = (-b ± √d) / 2a.'],
             ['Discriminant<0 means?',['Two real','One real','Complex','Zero'],2,'Negative discriminant → complex roots.'],
             ['Quadratic degree?',['1','2','3','0'],1,'Quadratic = degree 2.']],
            [['Quadratic Formula','x=(-b±√(b²-4ac))/2a'],['Discriminant','b²-4ac: determines number/type of roots.'],['Factoring','(x-r₁)(x-r₂)=0'],['Parabola','U-shaped graph of a quadratic function.']]),
          lesson(21,7,3,'Functions & Graphs',
            'Function: maps each input to one output. Domain=inputs, Range=outputs. Types: linear, quadratic, exponential (aˣ), logarithmic. Transformations: f(x)+k shifts up, f(x+h) shifts left.',
            [['Domain represents?',['Outputs','Inputs','Graph','Slope'],1,'Domain = valid input (x) values.'],
             ['f(x)+3 shifts?',['Left 3','Right 3','Up 3','Down 3'],2,'Adding outside shifts graph up.'],
             ['Inverse of exponential?',['Polynomial','Logarithmic','Linear','Quadratic'],1,'Logarithm is inverse of exponentiation.']],
            [['Function','Maps each input to exactly one output: f(x).'],['Domain','All valid input values.'],['Range','All possible output values.'],['Exponential','f(x)=aˣ — multiplicative growth/decay.']]),
        ]},
      { _id: 8, name: 'Statistics', description: 'Data analysis and probability.',
        lessons: [
          lesson(22,8,1,'Descriptive Statistics',
            'Measures of center: Mean (average), Median (middle), Mode (most frequent). Spread: Range, Variance, Standard Deviation (√variance).',
            [['Median of [1,3,5,7,9]?',['3','5','7','1'],1,'Middle of 5 sorted items = 3rd = 5.'],
             ['Std dev is √ of?',['Mean','Range','Variance','Mode'],2,'Standard deviation = √variance.'],
             ['Mode is?',['Average','Middle value','Most frequent','Range'],2,'Mode = most frequently occurring value.']],
            [['Mean','Sum / count: Σx/n.'],['Median','Middle value when data is sorted.'],['Std Deviation','√(avg squared deviations from mean).'],['Variance','Avg squared deviations from mean.']]),
          lesson(23,8,2,'Probability',
            'P(A) = favorable/total; range 0–1. P(A or B)=P(A)+P(B)-P(A∩B). Independent: P(A∩B)=P(A)×P(B). Conditional: P(A|B)=P(A∩B)/P(B).',
            [['P(rolling 3 on fair die)?',['1/3','1/2','1/6','1/4'],2,'1 favorable out of 6 = 1/6.'],
             ['P(A and B) for independent events?',['P(A)+P(B)','P(A)×P(B)','P(A)-P(B)','P(A)/P(B)'],1,'Multiplication rule: P(A)×P(B).'],
             ['Impossible event probability?',['1','0.5','undefined','0'],3,'P=0 means cannot occur.']],
            [['Probability','P(A)=favorable/total; 0 to 1.'],['Independent Events','One outcome does not affect the other.'],['Conditional P','P(A|B) = P(A∩B)/P(B).'],["Bayes' Theorem",'Updates probability given new evidence.']]),
          lesson(24,8,3,'Distributions',
            'Normal: bell curve, symmetric. Empirical rule: 68% within ±1σ, 95% within ±2σ, 99.7% within ±3σ. Binomial: successes in n trials. Poisson: events in fixed time.',
            [['% within ±1σ (normal)?',['50%','68%','95%','99.7%'],1,'Empirical rule: ~68% within ±1σ.'],
             ['Normal distribution shape?',['Skewed right','Uniform','Bell curve','Exponential'],2,'Normal = symmetric bell curve.'],
             ['Within ±2σ?',['68%','95%','99.7%','50%'],1,'95% of data within 2 standard deviations.']],
            [['Normal Distribution','Symmetric bell curve; described by μ and σ.'],['Empirical Rule','68-95-99.7% within 1,2,3 std deviations.'],['Binomial Dist.','Models successes in n independent trials.'],['Standard Normal','μ=0, σ=1; uses z-scores.']]),
        ]},
      { _id: 9, name: 'Geometry', description: 'Shapes, space, and spatial reasoning.',
        lessons: [
          lesson(25,9,1,'Triangles & Angles',
            'Triangle angles sum to 180°. Types: equilateral (all equal), isosceles (two equal), scalene (all different). Pythagorean theorem: a²+b²=c². Area=(base×height)/2.',
            [['Triangle angles sum to?',['90°','180°','270°','360°'],1,'Always 180°.'],
             ['Right triangle legs 3,4 hypotenuse?',['5','7','6','√7'],0,'3²+4²=25=5².'],
             ['Equilateral has how many equal sides?',['1','2','3','0'],2,'All 3 sides equal.']],
            [['Pythagorean Theorem','a²+b²=c² for right triangles.'],['Hypotenuse','Longest side, opposite right angle.'],['Equilateral Triangle','All sides and angles (60°) equal.'],['Area of Triangle','(base×height)/2']]),
          lesson(26,9,2,'Circles & Pi',
            'Circle: equidistant points from center. Circumference=2πr. Area=πr². π≈3.14159 = circumference/diameter. Chord, arc, sector are circle parts.',
            [['Circumference radius=5?',['5π','10π','25π','2π'],1,'C=2π×5=10π.'],
             ['Area radius=3?',['3π','6π','9π','12π'],2,'A=π×9=9π.'],
             ['π = circumference / ?',['Radius','Area','Diameter','Arc'],2,'π=C/d.']],
            [['Circumference','C=2πr — perimeter of circle.'],['Area of Circle','A=πr²'],['π (Pi)','≈3.14159 = C/diameter.'],['Diameter','d=2r — across circle through center.']]),
          lesson(27,9,3,'3D Shapes & Volume',
            'Cube: V=s³. Rectangular prism: V=lwh. Sphere: V=(4/3)πr³, SA=4πr². Cylinder: V=πr²h. Cone: V=(1/3)πr²h.',
            [['Volume of cube side=3?',['9','18','27','81'],2,'V=3³=27.'],
             ['Volume of sphere?',['πr²','2πr²','(4/3)πr³','4πr³'],2,'V=(4/3)πr³.'],
             ['Surface area of cube?',['s²','4s²','6s²','s³'],2,'SA=6s² (6 faces).']],
            [['Volume of Cube','V=s³'],['Volume of Sphere','V=(4/3)πr³'],['Volume of Cylinder','V=πr²h'],['Surface Area Sphere','SA=4πr²']]),
        ]},
    ]},
  { _id: 4, name: 'Science', icon: '🔬', color: '#333333',
    description: 'Physics, chemistry, and biology.',
    subcategories: [
      { _id: 10, name: 'Physics', description: 'Laws governing motion and energy.',
        lessons: [
          lesson(28,10,1,"Newton's Laws",
            "1st (Inertia): Objects resist change in motion. 2nd: F=ma. 3rd: Every action has equal opposite reaction.",
            [['F=ma is Newton\'s?',['1st','2nd','3rd','Gravity'],1,'F=ma is Newton\'s 2nd Law.'],
             ['Pushed back in accelerating car = ?',['1st','2nd','3rd','Gravity'],0,'Inertia (1st law) — body resists change.'],
             ['Action/reaction act on?',['Same object','Different objects','Ground','Air'],1,'3rd law: forces act on different objects.']],
            [['Inertia','Tendency to resist changes in motion.'],['F=ma',"Newton's 2nd Law: Force=mass×acceleration."],["Newton's 3rd","Every action has equal opposite reaction."],['Net Force','Vector sum of all forces on an object.']]),
          lesson(29,10,2,'Energy & Work',
            'Work: W=Fd·cos(θ). KE=½mv² (kinetic). PE=mgh (potential). Conservation: energy is never created/destroyed. Power P=W/t in watts.',
            [['KE=?',['mgh','½mv²','Fd','mv'],1,'Kinetic energy=½×mass×velocity².'],
             ['PE depends on?',['Speed','Mass and height','Temperature','Charge'],1,'PE=mgh.'],
             ['Power measured in?',['Joules','Newtons','Watts','Kelvin'],2,'Power=W/t in watts.']],
            [['Kinetic Energy','KE=½mv² — energy of motion.'],['Potential Energy','PE=mgh — stored by position.'],['Conservation of Energy','Total energy of isolated system is constant.'],['Work','W=Fd·cos(θ) — energy transferred by force.']]),
          lesson(30,10,3,'Waves & Light',
            'Waves transfer energy. Transverse: oscillation ⊥ direction (light). Longitudinal: oscillation ∥ direction (sound). v=fλ. EM spectrum: radio→gamma at c≈3×10⁸ m/s.',
            [['Speed of light in vacuum?',['3×10⁶','3×10⁸','3×10¹⁰','3×10⁴'],1,'c≈3×10⁸ m/s.'],
             ['Sound is?',['Transverse','Longitudinal','EM','Standing'],1,'Sound = longitudinal compression wave.'],
             ['Wave speed=?',['f×λ','f/λ','λ/f','f+λ'],0,'v=fλ.']],
            [['Wavelength (λ)','Distance between wave peaks.'],['Frequency (f)','Waves per second (Hz).'],['EM Spectrum','Radio→Micro→IR→Visible→UV→X-ray→Gamma.'],['v=fλ','Wave speed = frequency × wavelength.']]),
        ]},
      { _id: 11, name: 'Chemistry', description: 'Atoms, bonds, and reactions.',
        lessons: [
          lesson(31,11,1,'Atoms & Periodic Table',
            'Atom: nucleus (protons+neutrons) + electrons. Atomic number=protons. Periodic table: periods (rows), groups (cols). Group 1=alkali, 17=halogens, 18=noble gases.',
            [["Element's identity determined by?",['Neutrons','Electrons','Protons','Mass number'],2,'Atomic number (protons) identifies the element.'],
             ['Noble gases in group?',['1','2','17','18'],3,'Group 18 = noble gases.'],
             ['Mass number = protons + ?',['Electrons','Neutrons','Isotopes','Quarks'],1,'Mass number = protons+neutrons.']],
            [['Atomic Number','Protons in nucleus; identifies element.'],['Mass Number','Protons+neutrons.'],['Isotopes','Same element, different neutron count.'],['Periodic Table','Elements by atomic number in periods/groups.']]),
          lesson(32,11,2,'Chemical Bonds',
            'Ionic: electron transfer (metal→nonmetal), e.g. NaCl. Covalent: electron sharing (nonmetals). Polar covalent: unequal sharing. Hydrogen bonds: δ+H...δ- atom; gives water unique properties.',
            [['NaCl forms via?',['Covalent','Hydrogen','Ionic','Metallic'],2,'NaCl = ionic bond.'],
             ['Covalent bonds involve?',['Electron transfer','Electron sharing','Both','Neither'],1,'Covalent = shared electrons.'],
             ['H₂O molecules held together by?',['Ionic','Covalent within, H-bonds between','Metallic','Van der Waals only'],1,'Within H₂O: covalent. Between: hydrogen bonds.']],
            [['Ionic Bond','Electron transfer; forms ions.'],['Covalent Bond','Electron sharing between nonmetals.'],['Polar Covalent','Unequal sharing; partial charges.'],['Hydrogen Bond','δ+H attracted to electronegative atom.']]),
          lesson(33,11,3,'Chemical Reactions',
            'Reactions transform reactants to products. Conservation of mass: atoms balanced. Types: synthesis, decomposition, combustion, acid-base. Catalysts speed without being consumed.',
            [['Catalyst?',['Is consumed','Speeds without being consumed','Slows reaction','Changes products'],1,'Catalysts lower activation energy and are not consumed.'],
             ['Combustion produces?',['Only H₂O','Only CO₂','CO₂ and H₂O','O₂ and N₂'],2,'Combustion of hydrocarbon → CO₂+H₂O.'],
             ['Conservation of mass?',['Energy is constant','Atoms not created/destroyed','Temperature preserved','Volume constant'],1,'Mass (atoms) is conserved in reactions.']],
            [['Reactants','Substances entering a reaction.'],['Products','Substances formed by reaction.'],['Catalyst','Speeds reaction; not consumed.'],['Combustion','Fuel+O₂→CO₂+H₂O+energy.']]),
        ]},
      { _id: 12, name: 'Biology', description: 'Life, cells, genetics, and evolution.',
        lessons: [
          lesson(34,12,1,'The Cell',
            'Cell = basic unit of life. Prokaryotic (bacteria): no nucleus. Eukaryotic: membrane-bound nucleus, organelles. Key: nucleus (DNA), mitochondria (ATP), ribosomes (proteins), chloroplasts (photosynthesis in plants).',
            [['Energy organelle?',['Nucleus','Ribosome','Mitochondria','Vacuole'],2,'Mitochondria produce ATP.'],
             ['Prokaryotes lack?',['Ribosomes','Cell membrane','Membrane-bound nucleus','DNA'],2,'Prokaryotes have no membrane-bound nucleus.'],
             ['Protein synthesis at?',['Mitochondria','Golgi','Ribosomes','Nucleus'],2,'Ribosomes translate mRNA to proteins.']],
            [['Mitochondria','Produces ATP via cellular respiration.'],['Nucleus','Contains DNA; controls cell.'],['Ribosome','Site of protein synthesis.'],['Chloroplast','Converts sunlight to sugar via photosynthesis.']]),
          lesson(35,12,2,'DNA & Genetics',
            'DNA: double helix, bases A-T, C-G. Genes encode proteins. Dominant alleles mask recessive. Genotype=genetic code; phenotype=observable trait. Mutations: changes in DNA sequence.',
            [['A pairs with?',['C','G','T','U'],2,'A pairs with T in DNA.'],
             ['Dominant allele?',['Always harmful','Masks recessive','Is rarer','Only in males'],1,'Dominant is expressed with one copy.'],
             ['DNA shaped like?',['Single strand','Triple helix','Double helix','Circle'],2,'DNA = double helix.']],
            [['DNA','Double-helix polymer: A-T, C-G bases.'],['Gene','DNA segment encoding a protein.'],['Dominant Allele','Expressed even with one copy.'],['Mutation','Change in DNA sequence.']]),
          lesson(36,12,3,'Evolution',
            'Evolution: change in heritable traits over generations. Darwin: natural selection — fitter individuals reproduce more. Evidence: fossils, anatomy, DNA. Speciation: reproductive isolation → new species.',
            [['Proposed natural selection?',['Mendel','Einstein','Darwin','Lamarck'],2,'Darwin proposed natural selection (1859).'],
             ['Natural selection driven by?',['Random mutation only','Traits improving survival/reproduction','Human choice','Climate alone'],1,'Fitness determines which traits spread.'],
             ['Speciation requires?',['Genetic identity','Reproductive isolation','Larger population','Extinction'],1,'Isolation prevents gene flow → divergence.']],
            [['Natural Selection','Fitter individuals survive and reproduce more.'],['Fitness','Ability to survive and reproduce.'],['Speciation','New species from reproductive isolation.'],['Genetic Drift','Random allele frequency change in small populations.']]),
        ]},
    ]},
  { _id: 5, name: 'History', icon: '📜', color: '#444444',
    description: 'Key events and eras that shaped civilization.',
    subcategories: [
      { _id: 13, name: 'Ancient History', description: 'Civilizations of the ancient world.',
        lessons: [
          lesson(37,13,1,'Ancient Egypt',
            'Egypt thrived along the Nile for 3000+ years. Pharaohs were divine rulers. Hieroglyphics = writing system. Great Pyramid of Giza (2560 BCE) = only surviving ancient Wonder. Rosetta Stone decoded hieroglyphics.',
            [['Central river?',['Tigris','Euphrates','Nile','Amazon'],2,'The Nile was central to Egyptian civilization.'],
             ['Great Pyramid was?',['Temple','Palace','Royal tomb','Library'],2,'Pyramids were royal tombs.'],
             ['Rosetta Stone helped decode?',['Latin','Cuneiform','Hieroglyphics','Sanskrit'],2,'Rosetta Stone: Greek+Demotic+Hieroglyphics.']],
            [['Pharaoh','Divine ruler of ancient Egypt.'],['Hieroglyphics','Egyptian pictographic writing.'],['Rosetta Stone','Enabled decoding of hieroglyphics (196 BCE).'],['Great Pyramid','Built ~2560 BCE for Pharaoh Khufu.']]),
          lesson(38,13,2,'Greece & Rome',
            'Greece (800-146 BCE): democracy, philosophy, Olympics. Athens developed democracy. Philosophers: Socrates, Plato, Aristotle. Rome: Republic (509 BCE) → Empire (27 BCE). Augustus = first emperor. Western Empire fell 476 CE.',
            [["Plato's teacher?",['Aristotle','Socrates','Alexander','Pericles'],1,'Socrates taught Plato.'],
             ['Western Rome fell?',['27 BCE','476 CE','1453 CE','330 CE'],1,'476 CE = fall of Western Rome.'],
             ["Rome's first emperor?",['Julius Caesar','Nero','Augustus','Trajan'],2,'Augustus (27 BCE).']],
            [['Democracy','Developed Athens ~508 BCE.'],['Socrates','Greek philosopher ~470-399 BCE.'],['Roman Republic','509-27 BCE; Senate and consuls.'],['Augustus','First Roman Emperor (27 BCE-14 CE).']]),
          lesson(39,13,3,'Mesopotamia',
            'Between Tigris and Euphrates. Sumer (~4500 BCE) invented cuneiform — earliest writing. Hammurabi (~1754 BCE) wrote one of the first law codes. Called "Cradle of Civilization".',
            [['Earliest writing system?',['Hieroglyphics','Cuneiform','Latin','Sanskrit'],1,'Cuneiform = oldest known writing.'],
             ["Hammurabi's Code was?",['Religious text','Trade agreement','Law code','Astronomy'],2,"One of the first written law codes."],
             ['Between which rivers?',['Nile+Congo','Tigris+Euphrates','Amazon+Orinoco','Indus+Ganges'],1,'Mesopotamia = land between the rivers.']],
            [['Mesopotamia','Between Tigris+Euphrates; birthplace of writing.'],['Cuneiform','Earliest writing, by Sumerians (~3400 BCE).'],["Hammurabi's Code",'Early law code (~1754 BCE).'],['Sumer','Ancient civilization; invented writing.']]),
        ]},
      { _id: 14, name: 'World Wars', description: 'Conflicts that reshaped the 20th century.',
        lessons: [
          lesson(40,14,1,'World War I',
            'WWI (1914-1918). Triggered by assassination of Archduke Franz Ferdinand. MAIN causes: Militarism, Alliances, Imperialism, Nationalism. Trench warfare on Western Front. Ended Armistice Nov 11, 1918. Treaty of Versailles 1919.',
            [['WWI triggered by assassination of?',['Kaiser Wilhelm','Archduke Franz Ferdinand','Tsar Nicholas','Churchill'],1,'Assassination of Franz Ferdinand June 28, 1914.'],
             ['MAIN: M-A-I-N last letter?',['Navigation','Nationalism','Neutrality','Nobility'],1,'MAIN = Militarism, Alliances, Imperialism, Nationalism.'],
             ['WWI Armistice date?',['June 28 1919','Nov 11 1918','Sep 2 1945','July 4 1776'],1,'Armistice = November 11, 1918.']],
            [['Triple Entente','France, Russia, Britain in WWI.'],['Trench Warfare','Defensive trenches; stalemate on Western Front.'],['Armistice','Stop-fighting agreement; WWI ended Nov 11, 1918.'],['Treaty of Versailles','1919; blamed Germany for WWI.']]),
          lesson(41,14,2,'World War II',
            'WWII (1939-1945); ~70-85M deaths. Germany invaded Poland Sep 1, 1939. Axis vs Allies. Holocaust: 6M Jews murdered. D-Day June 6, 1944. Germany surrendered May 8, 1945 (V-E Day). Japan Sep 2, 1945 (V-J Day) after atomic bombs.',
            [['WWII started by invasion of?',['France','USSR','Poland','Denmark'],2,'Germany invaded Poland Sep 1, 1939.'],
             ['D-Day was?',['June 6 1944','Sep 1 1939','May 8 1945','Dec 7 1941'],0,'D-Day = June 6, 1944.'],
             ['Pacific war ended by?',['D-Day','Battle of Midway','Atomic bombs','Berlin invasion'],2,'Atomic bombs on Japan led to V-J Day.']],
            [['Axis Powers','Germany, Italy, Japan.'],['Holocaust','Nazi genocide of 6M+ Jews and others.'],['D-Day','Allied Normandy invasion, June 6, 1944.'],['V-E Day','Victory in Europe, May 8, 1945.']]),
          lesson(42,14,3,'The Cold War',
            'Cold War (1947-1991): USA (capitalism) vs USSR (communism). Arms race, MAD doctrine. Key events: Berlin Blockade, Korean War, Cuban Missile Crisis, Vietnam War, Moon landing. Berlin Wall fell 1989. USSR dissolved 1991.',
            [['Cold War between USA and?',['China','USSR','Germany','Japan'],1,'USA vs USSR.'],
             ['MAD stands for?',['Military Aggressive Defense','Mutually Assured Destruction','Multiple Deployments','Mass Arms'],1,'MAD = Mutually Assured Destruction.'],
             ['Berlin Wall fell?',['1945','1962','1989','1991'],2,'November 9, 1989.']],
            [['Cold War','USA vs USSR ideological conflict 1947-1991.'],['MAD','Mutually Assured Destruction — nuclear deterrence.'],['Cuban Missile Crisis','1962: closest to nuclear war.'],['Berlin Wall','Divided East/West Berlin 1961-1989.']]),
        ]},
      { _id: 15, name: 'Modern Era', description: 'The world from the 20th century to today.',
        lessons: [
          lesson(43,15,1,'Globalization',
            'Globalization: increasing interconnection of economies, cultures, societies. Drivers: trade, internet, multinationals, WTO/IMF/UN. Benefits: growth, tech spread. Challenges: inequality, cultural loss, environmental damage.',
            [['Promotes global trade?',['NATO','WTO','WHO','UNICEF'],1,'WTO regulates international trade.'],
             ['Major globalization driver?',['Protectionism','The internet','Tariffs','Isolationism'],1,'Internet enables instant global commerce.'],
             ['Globalization challenge?',['More jobs everywhere','Less inequality','Income inequality','Cheaper goods'],2,'Benefits are unevenly distributed.']],
            [['Globalization','Interconnection of world economies and cultures.'],['WTO','World Trade Organization.'],['Multinational','Company operating in multiple countries.'],['Outsourcing','Hiring abroad for lower-cost services.']]),
          lesson(44,15,2,'Digital Revolution',
            "Digital Revolution (~1970s+): PCs, WWW (1991 Tim Berners-Lee), smartphones (2007), social media. Moore's Law: transistors double every ~2 years. AI, Big Data, cloud computing define today.",
            [['Invented WWW?',['Gates','Jobs','Berners-Lee','Zuckerberg'],2,'Tim Berners-Lee invented the WWW (1991).'],
             ["Moore's Law: transistors double every?",['Year','Two years','Five years','Decade'],1,"~2 years."],
             ['Smartphone era began?',['Nokia 3310 2000','BlackBerry 2003','iPhone 2007','Android 2010'],2,'iPhone (2007) launched modern smartphone era.']],
            [['WWW','World Wide Web; Tim Berners-Lee 1991.'],["Moore's Law",'Transistors double every ~2 years.'],['Cloud Computing','Computing services over the internet.'],['AI','Systems performing tasks needing human intelligence.']]),
          lesson(45,15,3,'Climate Change',
            'Climate change: long-term temperature shifts accelerated by human activity. Greenhouse gases (CO₂, CH₄) trap heat. Consequences: rising seas, extreme weather, extinctions. Paris Agreement 2015: limit to 1.5-2°C.',
            [['Main human greenhouse gas?',['O₂','N₂','CO₂','Ar'],2,'CO₂ from fossil fuels drives climate change.'],
             ['Paris Agreement limits warming to?',['0.5°C','1.5-2°C','3°C','5°C'],1,'1.5-2°C above pre-industrial.'],
             ['Renewable energy?',['Coal and oil','Natural gas','Solar and wind','Nuclear only'],2,'Solar and wind are renewables.']],
            [['Greenhouse Effect','Gases trap solar heat; warm planet.'],['Paris Agreement','2015; limit warming 1.5-2°C.'],['Renewable Energy','Solar, wind, hydro — naturally replenished.'],['CO₂','Primary greenhouse gas from fossil fuels.']]),
        ]},
    ]},
  { _id: 6, name: 'Languages', icon: '🌐', color: '#555555',
    description: 'Grammar, writing, and communication skills.',
    subcategories: [
      { _id: 16, name: 'English Grammar', description: 'Master the rules of English.',
        lessons: [
          lesson(46,16,1,'Parts of Speech',
            'Eight parts: Noun (person/place/thing/idea), Pronoun (replaces noun), Verb (action/state), Adjective (modifies noun), Adverb (modifies verb/adj), Preposition (relationship), Conjunction (joins), Interjection (expression).',
            [['Modifies a noun?',['Adverb','Adjective','Preposition','Conjunction'],1,'Adjectives describe nouns.'],
             ['"Quickly" is?',['Adjective','Noun','Adverb','Preposition'],2,'"Quickly" modifies a verb — adverb.'],
             ['Joins clauses?',['Pronoun','Interjection','Conjunction','Article'],2,'Conjunctions join words, phrases, or clauses.']],
            [['Noun','Names person, place, thing, idea.'],['Verb','Expresses action or state of being.'],['Adjective','Modifies or describes a noun.'],['Adverb','Modifies verb, adjective, or adverb.']]),
          lesson(47,16,2,'Tenses',
            'Simple: walk/walked/will walk. Continuous: am/was/will be walking. Perfect: have/had/will have walked. Key: simple past (done) vs present perfect (still relevant): "I lost" vs "I have lost".',
            [['"She has finished" is?',['Simple past','Present continuous','Present perfect','Past perfect'],2,'"Has finished" = present perfect.'],
             ['Correct with "yesterday"?',['I have seen him yesterday','I saw him yesterday','Both','Neither'],1,'Specific past times require simple past.'],
             ['"Was eating when she called" uses?',['Simple+simple','Past cont+simple past','Past perfect+simple','Present+past'],1,'Past continuous + simple past.']],
            [['Simple Past','Completed action: "I walked."'],['Present Perfect','Past with present relevance: "I have walked."'],['Past Continuous','Ongoing past: "I was walking."'],['Future Simple','"I will walk."']]),
          lesson(48,16,3,'Punctuation',
            'Period: ends sentence. Comma: separates. Semicolon: joins independent clauses. Colon: introduces list. Apostrophe: possession (Sara\'s) or contraction (it\'s=it is). Em dash: emphasis.',
            [['Joins two independent clauses?',['Comma','Period','Semicolon','Colon'],2,'Semicolons join related independent clauses.'],
             ['"It\'s raining" apostrophe means?',['Possession','Contraction','Plural','Omission only'],1,'"It\'s" = "it is" — contraction.'],
             ['Colon used to?',['End sentence','Show possession','Introduce list/explanation','Replace comma'],2,'Colons introduce lists or elaborations.']],
            [['Semicolon','Joins independent clauses: "I came; I saw."'],['Colon','Introduces list or explanation.'],['Apostrophe (contraction)','"it\'s" = "it is"'],['Apostrophe (possession)',"Sara's book."]]),
        ]},
      { _id: 17, name: 'Spanish Basics', description: 'Start speaking Spanish.',
        lessons: [
          lesson(49,17,1,'Greetings',
            'Hola=Hello. Buenos días=Good morning. Buenas tardes=Good afternoon. Buenas noches=Good night. Me llamo=My name is. ¿Cómo estás?=How are you? Bien, gracias=Fine, thanks. Por favor=Please. De nada=You\'re welcome.',
            [['"Buenos días" means?',['Good night','Good afternoon','Good morning','Hello'],2,'"Buenos días" = Good morning.'],
             ['"My name is Ana" in Spanish?',['Soy Ana','Me llamo Ana','Tengo Ana','Llamo me Ana'],1,'"Me llamo Ana."'],
             ['"Gracias" means?',['Please','Sorry','Thank you','Welcome'],2,'"Gracias" = Thank you.']],
            [['Hola','Hello'],['Me llamo...','My name is...'],['¿Cómo estás?','How are you? (informal)'],['Gracias / De nada','Thank you / You\'re welcome']]),
          lesson(50,17,2,'Numbers & Colors',
            '1-10: uno,dos,tres,cuatro,cinco,seis,siete,ocho,nueve,diez. Colors: rojo=red, azul=blue, verde=green, amarillo=yellow, negro=black, blanco=white. Adjectives agree in gender/number with nouns.',
            [['"Cinco" means?',['4','5','6','7'],1,'"Cinco" = 5.'],
             ['"Azul" is?',['Red','Green','Blue','Yellow'],2,'"Azul" = blue.'],
             ['Spanish adjectives?',['Always masculine','Agree gender/number','Always after noun','Never change'],1,'Adjectives agree with noun in gender and number.']],
            [['uno, dos, tres','one, two, three'],['rojo / azul / verde','red / blue / green'],['negro / blanco','black / white'],['Adjective Agreement','Match noun gender (masc/fem) and number (sing/pl).']]),
          lesson(51,17,3,'Present Tense',
            'Regular -AR "hablar": hablo,hablas,habla,hablamos,habláis,hablan. -ER "comer": como,comes,come... Ser (permanent): soy,eres,es,somos... Estar (temporary): estoy,estás,está,estamos...',
            [['"Yo hablo" means?',['You speak','He speaks','I speak','We speak'],2,'"Yo hablo" = I speak.'],
             ['Temporary states use?',['Ser','Haber','Estar','Tener'],2,'"Estar" = temporary states.'],
             ['"Ellos comen" means?',['He eats','You eat','We eat','They eat'],3,'"Ellos comen" = They eat.']],
            [['Hablar (yo)','hablo — I speak'],['Ser vs Estar','Ser=permanent; Estar=temporary.'],['Comer (nosotros)','comemos — we eat'],['Yo/Tú/Él','I/You/He']]),
        ]},
      { _id: 18, name: 'Writing Skills', description: 'Structure, style, and communication.',
        lessons: [
          lesson(52,18,1,'Essay Structure',
            'Introduction: hook → context → thesis. Body paragraphs: topic sentence → evidence → conclusion. Conclusion: restate thesis → summary → insight. Thesis = central argument.',
            [['Thesis statement does?',['Summarizes conclusion','States central argument','Lists evidence','Introduces topic only'],1,'Thesis = main argument.'],
             ['Each body paragraph starts with?',['Quote','Topic sentence','Transition','Thesis restatement'],1,'Topic sentence states paragraph\'s main idea.'],
             ['Conclusion should?',['New arguments','Restate thesis/summarize','Repeat intro verbatim','End with question'],1,'Conclusions restate and synthesize.']],
            [['Thesis','Central argument stated in introduction.'],['Topic Sentence','First sentence of body paragraph.'],['Transitions','However, therefore, furthermore, in contrast.'],['Conclusion','Restates thesis and synthesizes points.']]),
          lesson(53,18,2,'Writing Clearly',
            'Active voice: "She wrote the report." Be concise. Specific language: "40% increase" not "significant increase". Vary sentence length. One main idea per paragraph. Revision is essential.',
            [['Active voice?',['Report was written by her','She wrote the report','It was done','Had been completed'],1,'"She wrote" — subject acts. Active voice.'],
             ['Concise means?',['Many examples','Complex vocab','Eliminating redundancy','Long paragraphs'],2,'Remove unnecessary words.'],
             ['Good paragraphs have?',['Multiple ideas','One main idea','No topic sentence','10+ sentences'],1,'One main idea per paragraph.']],
            [['Active Voice','Subject acts: "She wrote the report."'],['Passive Voice','Subject receives: "The report was written."'],['Concise Writing','Clear expression with no unnecessary words.'],['Revision','Reviewing and improving a draft.']]),
          lesson(54,18,3,'Persuasive Writing',
            'Persuasive: convince the reader. Rhetorical appeals: Logos (logic/facts), Ethos (credibility), Pathos (emotion). Structure: claim → evidence → counterarguments → call to action.',
            [['Logos appeals to?',['Emotions','Logic and reason','Authority','Ethics'],1,'Logos = logical arguments, facts.'],
             ['Ethos establishes?',["Reader's emotion","Writer's credibility","Logical structure","Counterargument"],1,"Ethos = writer's authority."],
             ['Addressing counterarguments?',['Weakens case','Shows bias','Strengthens case','Unnecessary'],2,'Refuting objections strengthens persuasiveness.']],
            [['Logos','Appeal through logic and evidence.'],['Ethos',"Appeal through writer's credibility."],['Pathos','Appeal through emotion.'],['Counterargument','Opposing view; addressing it strengthens yours.']]),
        ]},
    ]},
];

const games = [
  { _id:1,slug:'memory-cards',name:'Memory Cards',type:'memory',difficulty:'easy',description:'Flip cards to find matching pairs',instructions:'Click any card to flip it, then find its pair. Match all pairs to win.' },
  { _id:2,slug:'number-sequence',name:'Number Sequence',type:'sequence',difficulty:'medium',description:'Find the missing number in the sequence',instructions:'Study the sequence and choose the missing number.' },
  { _id:3,slug:'word-scramble',name:'Word Scramble',type:'word',difficulty:'easy',description:'Unscramble the letters to form a word',instructions:'Rearrange the letters to spell the correct word.' },
  { _id:4,slug:'math-sprint',name:'Math Sprint',type:'math',difficulty:'medium',description:'Solve arithmetic problems against the clock',instructions:'Answer as many math problems as you can in 60 seconds.' },
  { _id:5,slug:'pattern-match',name:'Pattern Match',type:'pattern',difficulty:'medium',description:'Identify and continue the visual pattern',instructions:'Study the pattern and select what comes next.' },
  { _id:6,slug:'simon-says',name:'Simon Says',type:'sequence',difficulty:'medium',description:'Remember and repeat the growing color sequence',instructions:'Watch the sequence of buttons light up, then repeat it in order.' },
  { _id:7,slug:'odd-one-out',name:'Odd One Out',type:'logic',difficulty:'easy',description:'Pick the item that does not belong',instructions:'Four items are shown — click the one that does not fit.' },
  { _id:8,slug:'anagram',name:'Anagram',type:'word',difficulty:'hard',description:'Rearrange letters to find the hidden word',instructions:'You are given a scrambled word. Type the correct word.' },
  { _id:9,slug:'sudoku-mini',name:'Mini Sudoku',type:'logic',difficulty:'hard',description:'Fill a 4×4 grid so each row and column has 1–4',instructions:'Click a cell and type 1–4. No repeats in any row, column, or 2×2 box.' },
  { _id:10,slug:'tower-of-hanoi',name:'Tower of Hanoi',type:'logic',difficulty:'hard',description:'Move all disks to the target peg',instructions:'Click a peg to pick up, click another to place. No larger disk on smaller.' },
  { _id:11,slug:'n-back',name:'N-Back',type:'memory',difficulty:'hard',description:'Does the position match 2 steps ago?',instructions:'A square lights up in a 3×3 grid. Press MATCH if current = 2 steps ago.' },
  { _id:12,slug:'stroop-test',name:'Stroop Test',type:'logic',difficulty:'medium',description:'Name the ink color, not the word',instructions:'Click the button matching the INK COLOR, not the word text.' },
  { _id:13,slug:'arithmetic-chain',name:'Arithmetic Chain',type:'math',difficulty:'medium',description:'Keep a running total through rapid operations',instructions:'Operations appear one by one. Enter the final result.' },
  { _id:14,slug:'visual-rotation',name:'Visual Rotation',type:'spatial',difficulty:'hard',description:'Match the rotated shape to the original',instructions:'Pick the rotated version that matches the shape on the left.' },
  { _id:15,slug:'word-chain',name:'Word Chain',type:'word',difficulty:'easy',description:'Change one letter at a time to reach the target word',instructions:'Change one letter per step to transform start into target word.' },
  { _id:16,slug:'true-false-logic',name:'Logic Statements',type:'logic',difficulty:'medium',description:'Evaluate logical statements as true or false',instructions:'Read each argument carefully and decide if the conclusion follows.' },
  { _id:17,slug:'color-memory',name:'Color Memory',type:'memory',difficulty:'easy',description:'Remember the order of flashing colors',instructions:'Colors flash in sequence. Repeat by clicking in the same order.' },
  { _id:18,slug:'matrix-pattern',name:'Matrix Pattern',type:'pattern',difficulty:'hard',description:'Select the missing piece that completes the matrix',instructions:'A 3×3 matrix has one piece missing. Select the correct answer.' },
  { _id:19,slug:'speed-math',name:'Speed Math',type:'math',difficulty:'easy',description:'Answer simple math problems as fast as possible',instructions:'Type the answer and press Enter. 30 seconds on the clock!' },
  { _id:20,slug:'spatial-blocks',name:'Spatial Blocks',type:'spatial',difficulty:'medium',description:'Count the total blocks in the 3D stack',instructions:'Count all blocks including hidden ones.' },
];

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log('Connected to MongoDB');
  await Category.deleteMany({});
  await Game.deleteMany({});
  await Category.insertMany(categories);
  console.log(`Seeded ${categories.length} categories`);
  await Game.insertMany(games);
  console.log(`Seeded ${games.length} games`);
  await mongoose.disconnect();
  console.log('Done.');
}

seed().catch(err => { console.error(err); process.exit(1); });
